name: Release to WordPress.org

on:
    release:
        types: [ released ]

jobs:
    build:
        uses: impress-org/givewp-github-actions/.github/workflows/wp-org-release.yml@master
        with:
            wp_org_slug: simple-social-shout-for-givewp
            zip_name: simple-social-shout-for-givewp
            text_domain: sss4givewp
            install_composer_packages: false
            install_npm_packages: false
        secrets:
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SLACK_ANNOUNCEMENT_WEBHOOK: ${{ secrets.SLACK_ANNOUNCEMENT_WEBHOOK }}
